# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'projectBasket' do
  
  use_frameworks!

  # Pods for projectBasket

  target 'projectBasketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire', '~> 4.4'

end
